apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-developer-binding
subjects:
- kind: Group
  name: developers
roleRef:
  kind: ClusterRole
  name: cluster-pod-logs
  apiGroup: rbac.authorization.k8s.io
