apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-secrets-binding
subjects:
- kind: Group
  name: admin-secrets
roleRef:
  kind: ClusterRole
  name: cluster-secrets-all-permissions
  apiGroup: rbac.authorization.k8s.io
