apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-writer-binding
subjects:
- kind: Group
  name: admin-cluster
roleRef:
  kind: ClusterRole
  name: cluster-pod-writer
  apiGroup: rbac.authorization.k8s.io
